# Makefile.config

# Compilers and tools
AS				:= nasm
CC				:= i686-elf-gcc
GDB				:= gdb
MFORMAT			:= mformat
MCOPY			:= mcopy
MMD				:= mmd
DD				:= dd
QEMU			:= qemu-system-i386
RM				:= rm -f
BOCHS			:= bochs
BOCHS_DBG		:= bochs -dbg

# Compile flags
CFLAGS			= -ffreestanding -Wall -Wextra -g
LDFLAGS			= -nostdlib -lgcc


define make_subdir
@for i in $(SUBDIR); do \
($(MAKE) -C $$i $1); \
done;
endef


%.bin : %.asm
	$(AS) -f bin -o $@ -l $*.lst $<

%.o : %.asm
	$(AS) -f elf32 -o $@ $<

%.o : %.c
	$(CC) $(CFLAGS) -c -o $@ $<
