# SPDX-FileCopyrightText: 2026 Zhan Zixuan
#
# SPDX-License-Identifier: MIT


include ../Makefile.config


BOOTSECT_BIN	= bootsect.bin
LOADER_BIN		= loader.bin


all : $(BOOTSECT_BIN) $(LOADER_BIN)

clean:
	$(RM) *.bin *.lst

.PHONY : all clean
